#!/bin/bash

DIR=$(cd "$(dirname "$0")" && pwd)

api () {
  curl -s 'https://aoe2.net/api/leaderboard?game=aoe2de&leaderboard_id=3&start='"$1"'&count='"$2"
}

readarray -t arr < <(api 1 1 | jq -c '.total, .leaderboard[0].rating' | tr -d '\r')

# see <https://stackoverflow.com/q/11003418> about xargs call
export -f api

seq 1 1000 "${arr[0]}" |
xargs -L 1 -P 10 -I {} bash -c "api {} 1000 | jq '.leaderboard | .[] | .rating'" |
awk -v hi="${arr[1]}" -f "$DIR"/hist.awk
