#!/bin/bash

api () {
  curl -s 'https://aoe2.net/api/leaderboard?game=aoe2de&leaderboard_id=3&start='"$1"'&count='"$2"
}

declare -a arr
readarray -t arr <<< "$(api 1 1 | jq '.total, .leaderboard[0].rating')"
n=${arr[0]//[!0-9]/}
top=${arr[1]//[!0-9]/}

i=1
{
  while [ $i -lt "$n" ]
  do
    api $i 1000 | jq '.leaderboard | .[] | .rating'
    i=$(( i + 1000 ))
  done
} | awk -v hi="$top" -f hist.awk > hist.txt
