#!/bin/bash

# see <https://mywiki.wooledge.org/BashFAQ/028> about accessing bundled files
# see <https://stackoverflow.com/q/11003418> about xargs call

cd "${BASH_SOURCE%/*}/" || exit

api () {
  curl -s 'https://aoe2.net/api/leaderboard?game=aoe2de&leaderboard_id=3&start='"$1"'&count='"$2"
}

n=$(api 1 1 | jq '.total')

export -f api

seq 1 1000 "$n" |
xargs -L 1 -P 10 -I {} bash -c "api {} 1000 | jq '.leaderboard | .[] | .rating'" |
awk -v bin=100 -f histogram.awk
