#!/bin/bash
#
# Requires the $GIST_TOKEN environment variable to be set
#
# Usage
# -----
# $ ./update-gist GIST_ID FILE

jq --compact-output --arg f "$2" '{files: {($f): {content: . | tojson }}}' "$2" |
	curl \
  	--silent \
		-X POST \
		-H 'Accept: application/vnd.github.v3+json' \
		-H "Authorization: token $GIST_TOKEN" \
		--data-binary @- \
		"https://api.github.com/gists/$1"
