#!/bin/bash
#
# This script collects rating data from the AoE2.net API and
# calculates a couple of statistics on the data.
# The output is written to stdout in JSON format.
#
# The AWK program takes a list of numbers separated by newlines
# and outputs the total count and median.
#  - Filtering values higher than 3000 (arbitrary) as the API seems to
#    send out crap sometimes.
#
# Additionally, a file `raw.txt` is written with intermediate values.
#
# Usage
# -----
# $ ./fetch-stats > stats.json
#
# References
# ----------
# <https://stackoverflow.com/q/11003418>: bash function with xargs

api() {
  curl -s "https://aoe2.net/api/leaderboard?game=aoe2de&leaderboard_id=3&start=$1&count=$2"
}

export -f api

set -o pipefail
seq 1 1000 "$(api 1 1 | jq '.total')" \
  | xargs -P 10 -I {} bash -c "api {} 1000 | jq '.leaderboard | .[] | .rating'" \
  | awk '$1 > 0 && $1 < 3000 { print $1 }' \
  | tee filtered.txt \
  | sort -n \
  | awk '
      { arr[i++] = $1 }

      END {
        if (i % 2) {
          median = arr[int(i / 2)]
        } else {
          m = int(i / 2)
          median = (arr[m - 1] + arr[m]) / 2
        }

        print(i, median)
      }' \
  | jq --slurp --compact-output '
      {
        stats: {
          count: .[0],
          median: .[1]
        },
          date: now | todate
      }'
